name             'windows_applications'
maintainer       'Todd Pigram'
maintainer_email 'todd@toddpigram.com'
license          'Apache 2.0'
description      'Installs/Configures windows_applications'
long_description 'Installs/Configures windows_applications'
version          '0.2.14'
depends          'windows'
depends          'chocolatey'
supports         'windows'
